export const MSSB_CHARACTERS = [
    {
      "Name": "Mario",
      "Bat": " 7",
      "Lean": " 0",
      "Zone": " 3",
      "Agility": " 2",
      "Coverage": " 6.75",
      "ReachOut": " 0",
      "ReachIn": " 0.75",
      "Run": " 7",
      "Field": " 6",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 9",
      "Pitch": " 6",
      "Stamina": " 8",
      "Curve": " 6",
      "Velocity": " 33",
      "ChargVelocity": " 24",
      "ChangeUp": " 2"
    },
    {
      "Name": "Luigi",
      "Bat": " 6",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 7",
      "Field": " 7",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 3",
      "Jump": " 3",
      "Chemistry": " 3",
      "Pitch": " 6",
      "Stamina": " 7",
      "Curve": " 5",
      "Velocity": " 33",
      "ChargVelocity": " 24",
      "ChangeUp": " 2"
    },
    {
      "Name": "Peach",
      "Bat": " 4",
      "Lean": " 1",
      "Zone": " 3",
      "Agility": " 3",
      "Coverage": " 8",
      "ReachOut": " 0",
      "ReachIn": " 2",
      "Run": " 5",
      "Field": " 8",
      "Dive": " 2",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 7",
      "Pitch": " 9",
      "Stamina": " 7",
      "Curve": " 9",
      "Velocity": " 35",
      "ChargVelocity": " 27",
      "ChangeUp": " 2.5"
    },
    {
      "Name": "Daisy",
      "Bat": " 6",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8.25",
      "ReachOut": " 0.5",
      "ReachIn": " 1.75",
      "Run": " 5",
      "Field": " 8",
      "Dive": " 3",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 7",
      "Stamina": " 6",
      "Curve": " 5",
      "Velocity": " 33",
      "ChargVelocity": " 24",
      "ChangeUp": " 2"
    },
    {
      "Name": "Birdo",
      "Bat": " 8",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 0.75",
      "ReachIn": " 0.75",
      "Run": " 5",
      "Field": " 7",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 8",
      "Pitch": " 4",
      "Stamina": " 6",
      "Curve": " 4",
      "Velocity": " 33",
      "ChargVelocity": " 24",
      "ChangeUp": " 2"
    },
    {
      "Name": "Wario",
      "Bat": " 8",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 0.75",
      "ReachIn": " 0.75",
      "Run": " 4",
      "Field": " 3",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 2",
      "Pitch": " 5",
      "Stamina": " 9",
      "Curve": " 3",
      "Velocity": " 31",
      "ChargVelocity": " 22",
      "ChangeUp": " 1"
    },
    {
      "Name": "Waluigi",
      "Bat": " 4",
      "Lean": " 1",
      "Zone": " 1",
      "Agility": " 2",
      "Coverage": " 8",
      "ReachOut": " 1.5",
      "ReachIn": " 0.5",
      "Run": " 5",
      "Field": " 8",
      "Dive": " 2",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 2",
      "Pitch": " 8",
      "Stamina": " 5",
      "Curve": " 3.5",
      "Velocity": " 29",
      "ChargVelocity": " 36",
      "ChangeUp": " 2"
    },
    {
      "Name": "Bowser",
      "Bat": " 10",
      "Lean": " 0",
      "Zone": " 1",
      "Agility": " 1",
      "Coverage": " 9.25",
      "ReachOut": " 2.5",
      "ReachIn": " 0.75",
      "Run": " 3",
      "Field": " 3",
      "Dive": " 2",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 10",
      "Pitch": " 5",
      "Stamina": " 7",
      "Curve": " 0",
      "Velocity": " 27",
      "ChargVelocity": " 22",
      "ChangeUp": " 2"
    },
    {
      "Name": "Bowser Jr.",
      "Bat": " 7",
      "Lean": " 2",
      "Zone": " 3",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 0.75",
      "ReachIn": " 0.75",
      "Run": " 7",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 8",
      "Pitch": " 5",
      "Stamina": " 8",
      "Curve": " 7",
      "Velocity": " 46",
      "ChargVelocity": " 25",
      "ChangeUp": " 3"
    },
    {
      "Name": "Donkey Kong",
      "Bat": " 9",
      "Lean": " 2",
      "Zone": " 1",
      "Agility": " 1",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 2",
      "Field": " 3",
      "Dive": " 2",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 3",
      "Chemistry": " 5",
      "Pitch": " 6",
      "Stamina": " 10",
      "Curve": " 2",
      "Velocity": " 26",
      "ChargVelocity": " 21",
      "ChangeUp": " 1"
    },
    {
      "Name": "Diddy Kong",
      "Bat": " 4",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 6",
      "Field": " 8",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 3",
      "Chemistry": " 4",
      "Pitch": " 5",
      "Stamina": " 6",
      "Curve": " 4.5",
      "Velocity": " 32",
      "ChargVelocity": " 26",
      "ChangeUp": " 2"
    },
    {
      "Name": "Dixie Kong",
      "Bat": " 3",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 0.5",
      "ReachIn": " 1",
      "Run": " 7",
      "Field": " 8",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 3",
      "Chemistry": " 5",
      "Pitch": " 3",
      "Stamina": " 5",
      "Curve": " 5",
      "Velocity": " 35",
      "ChargVelocity": " 28",
      "ChangeUp": " 1.5"
    },
    {
      "Name": "Funky Kong",
      "Bat": " 8",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 1",
      "Coverage": " 8",
      "ReachOut": " 1.5",
      "ReachIn": " 0.5",
      "Run": " 3",
      "Field": " 6",
      "Dive": " 2",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 3",
      "Chemistry": " 5",
      "Pitch": " 4",
      "Stamina": " 10",
      "Curve": " 0.5",
      "Velocity": " 27",
      "ChargVelocity": " 29",
      "ChangeUp": " 2.5"
    },
    {
      "Name": "Tiny Kong",
      "Bat": " 5",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 0.5",
      "ReachIn": " 1",
      "Run": " 5",
      "Field": " 7",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 3",
      "Chemistry": " 5",
      "Pitch": " 5",
      "Stamina": " 7",
      "Curve": " 3.5",
      "Velocity": " 33",
      "ChargVelocity": " 23",
      "ChangeUp": " 3"
    },
    {
      "Name": "Yoshi",
      "Bat": " 4",
      "Lean": " 1.5",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 9",
      "Field": " 6",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 4",
      "Stamina": " 7",
      "Curve": " 3",
      "Velocity": " 32",
      "ChargVelocity": " 25",
      "ChangeUp": " 1"
    },
    {
      "Name": "Red Yoshi",
      "Bat": " 4",
      "Lean": " 1.5",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 8",
      "Field": " 4",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 3",
      "Stamina": " 6",
      "Curve": " 3.5",
      "Velocity": " 36",
      "ChargVelocity": " 25",
      "ChangeUp": " 1.5"
    },
    {
      "Name": "Blue Yoshi",
      "Bat": " 2",
      "Lean": " 1.5",
      "Zone": " 1",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 8",
      "Field": " 6",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 4",
      "Stamina": " 7",
      "Curve": " 3.5",
      "Velocity": " 35",
      "ChargVelocity": " 25",
      "ChangeUp": " 1"
    },
    {
      "Name": "Yellow Yoshi",
      "Bat": " 4",
      "Lean": " 1.5",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 7",
      "Field": " 6",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 3",
      "Stamina": " 7",
      "Curve": " 4",
      "Velocity": " 36",
      "ChargVelocity": " 25",
      "ChangeUp": " 1"
    },
    {
      "Name": "Light Blue Yoshi",
      "Bat": " 3",
      "Lean": " 1.5",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 8",
      "Field": " 6",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 3",
      "Stamina": " 7",
      "Curve": " 4",
      "Velocity": " 36",
      "ChargVelocity": " 25",
      "ChangeUp": " 1"
    },
    {
      "Name": "Pink Yoshi",
      "Bat": " 3",
      "Lean": " 1.5",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 9",
      "Field": " 6",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 2",
      "Stamina": " 7",
      "Curve": " 3.5",
      "Velocity": " 35",
      "ChargVelocity": " 27",
      "ChangeUp": " 1"
    },
    {
      "Name": "King K. Rool",
      "Bat": " 10",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 1",
      "Coverage": " 7.75",
      "ReachOut": " 1.5",
      "ReachIn": " 0.25",
      "Run": " 1",
      "Field": " 2",
      "Dive": " 2",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 6",
      "Stamina": " 4",
      "Curve": " 1",
      "Velocity": " 26",
      "ChargVelocity": " 20",
      "ChangeUp": " 2.5"
    },
    {
      "Name": "Goomba",
      "Bat": " 3",
      "Lean": " 3",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.25",
      "ReachOut": " 0.75",
      "ReachIn": " 0.5",
      "Run": " 4",
      "Field": " 6",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 6",
      "Stamina": " 7",
      "Curve": " 9",
      "Velocity": " 47",
      "ChargVelocity": " 38",
      "ChangeUp": " 3.5"
    },
    {
      "Name": "Paragoomba",
      "Bat": " 3",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7",
      "ReachOut": " 0.5",
      "ReachIn": " 0.5",
      "Run": " 5",
      "Field": " 7",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 3",
      "Chemistry": " 5",
      "Pitch": " 6",
      "Stamina": " 6",
      "Curve": " 6",
      "Velocity": " 39",
      "ChargVelocity": " 30",
      "ChangeUp": " 2"
    },
    {
      "Name": "Boo",
      "Bat": " 3",
      "Lean": " 1",
      "Zone": " 3",
      "Agility": " 3",
      "Coverage": " 7.5",
      "ReachOut": " 0.75",
      "ReachIn": " 0.75",
      "Run": " 5",
      "Field": " 3",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 7",
      "Pitch": " 9",
      "Stamina": " 5",
      "Curve": " 8",
      "Velocity": " 36",
      "ChargVelocity": " 23",
      "ChangeUp": " 2"
    },
    {
      "Name": "King Boo",
      "Bat": " 7",
      "Lean": " 0",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8",
      "ReachOut": " 1",
      "ReachIn": " 1",
      "Run": " 4",
      "Field": " 3",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 7",
      "Stamina": " 5",
      "Curve": " 8",
      "Velocity": " 34",
      "ChargVelocity": " 26",
      "ChangeUp": " 2"
    },
    {
      "Name": "Petey Piranha",
      "Bat": " 10",
      "Lean": " 3",
      "Zone": " 1",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 1",
      "ReachIn": " 0.75",
      "Run": " 2",
      "Field": " 5",
      "Dive": " 3",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 4",
      "Stamina": " 10",
      "Curve": " 0",
      "Velocity": " 28",
      "ChargVelocity": " 20",
      "ChangeUp": " 1"
    },
    {
      "Name": "Wiggler",
      "Bat": " 7",
      "Lean": " 0",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 1",
      "ReachIn": " 0.75",
      "Run": " 7",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 3",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 3",
      "Stamina": " 8",
      "Curve": " 1.5",
      "Velocity": " 32",
      "ChargVelocity": " 28",
      "ChangeUp": " 2.5"
    },
    {
      "Name": "Monty Mole",
      "Bat": " 4",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8.25",
      "ReachOut": " 1.5",
      "ReachIn": " 0.75",
      "Run": " 7",
      "Field": " 5",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 4",
      "Stamina": " 5",
      "Curve": " 5.5",
      "Velocity": " 37",
      "ChargVelocity": " 29",
      "ChangeUp": " 1"
    },
    {
      "Name": "Blooper",
      "Bat": " 4",
      "Lean": " 0",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 1",
      "ReachIn": " 0.75",
      "Run": " 6",
      "Field": " 5",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 6",
      "Stamina": " 6",
      "Curve": " 8.5",
      "Velocity": " 43",
      "ChargVelocity": " 32",
      "ChangeUp": " 2.5"
    },
    {
      "Name": "Baby Mario",
      "Bat": " 3",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 0",
      "ReachIn": " 1.5",
      "Run": " 8",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 5",
      "Stamina": " 6",
      "Curve": " 5.5",
      "Velocity": " 42",
      "ChargVelocity": " 28",
      "ChangeUp": " 1"
    },
    {
      "Name": "Baby Luigi",
      "Bat": " 2",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 1",
      "ReachIn": " 0.75",
      "Run": " 8",
      "Field": " 5",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 5",
      "Stamina": " 5",
      "Curve": " 8",
      "Velocity": " 42",
      "ChargVelocity": " 28",
      "ChangeUp": " 2"
    },
    {
      "Name": "Baby Peach",
      "Bat": " 2",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 3",
      "Coverage": " 7.25",
      "ReachOut": " 0.25",
      "ReachIn": " 1",
      "Run": " 6",
      "Field": " 5",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 8",
      "Pitch": " 8",
      "Stamina": " 5",
      "Curve": " 10",
      "Velocity": " 42",
      "ChargVelocity": " 29",
      "ChangeUp": " 2"
    },
    {
      "Name": "Baby Daisy",
      "Bat": " 4",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 6",
      "Field": " 5",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 6",
      "Stamina": " 5",
      "Curve": " 5.5",
      "Velocity": " 37",
      "ChargVelocity": " 29",
      "ChangeUp": " 2"
    },
    {
      "Name": "Baby DK",
      "Bat": " 6",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 4",
      "Field": " 8",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 3",
      "Jump": " 3",
      "Chemistry": " 8",
      "Pitch": " 3",
      "Stamina": " 5",
      "Curve": " 3",
      "Velocity": " 35",
      "ChargVelocity": " 26",
      "ChangeUp": " 2.5"
    },
    {
      "Name": "Toadette",
      "Bat": " 3",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8.75",
      "ReachOut": " 0.75",
      "ReachIn": " 2",
      "Run": " 8",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 8",
      "Pitch": " 5",
      "Stamina": " 5",
      "Curve": " 5",
      "Velocity": " 31",
      "ChargVelocity": " 26",
      "ChangeUp": " 1"
    },
    {
      "Name": "Toadsworth",
      "Bat": " 3",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 3",
      "Field": " 7",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 8",
      "Pitch": " 7",
      "Stamina": " 4",
      "Curve": " 10",
      "Velocity": " 69",
      "ChargVelocity": " 43",
      "ChangeUp": " 4"
    },
    {
      "Name": "Red Toad",
      "Bat": " 5",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 9.75",
      "ReachOut": " 0.75",
      "ReachIn": " 3",
      "Run": " 7",
      "Field": " 3",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 7",
      "Pitch": " 5",
      "Stamina": " 6",
      "Curve": " 5",
      "Velocity": " 37",
      "ChargVelocity": " 22",
      "ChangeUp": " 1"
    },
    {
      "Name": "Blue Toad",
      "Bat": " 6",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 6.5",
      "ReachOut": " 0.75",
      "ReachIn": " -0.25",
      "Run": " 7",
      "Field": " 3",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 7",
      "Pitch": " 4",
      "Stamina": " 5",
      "Curve": " 5",
      "Velocity": " 36",
      "ChargVelocity": " 22",
      "ChangeUp": " 1"
    },
    {
      "Name": "Yellow Toad",
      "Bat": " 6",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 6.5",
      "ReachOut": " 0.75",
      "ReachIn": " -0.25",
      "Run": " 7",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 7",
      "Pitch": " 3",
      "Stamina": " 5",
      "Curve": " 4",
      "Velocity": " 37",
      "ChargVelocity": " 25",
      "ChangeUp": " 2"
    },
    {
      "Name": "Green Toad",
      "Bat": " 5",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 6.5",
      "ReachOut": " 0.75",
      "ReachIn": " -0.25",
      "Run": " 7",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 7",
      "Pitch": " 4",
      "Stamina": " 6",
      "Curve": " 5",
      "Velocity": " 34",
      "ChargVelocity": " 22",
      "ChangeUp": " 2.5"
    },
    {
      "Name": "Purple Toad",
      "Bat": " 6",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 6.5",
      "ReachOut": " 0.75",
      "ReachIn": " -0.25",
      "Run": " 7",
      "Field": " 2",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 7",
      "Pitch": " 5",
      "Stamina": " 5",
      "Curve": " 5",
      "Velocity": " 34",
      "ChargVelocity": " 24",
      "ChangeUp": " 2"
    },
    {
      "Name": "Blue Pianta",
      "Bat": " 8",
      "Lean": " 0",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.25",
      "ReachOut": " 0.75",
      "ReachIn": " 0.5",
      "Run": " 2",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 7",
      "Pitch": " 5",
      "Stamina": " 5",
      "Curve": " 2.5",
      "Velocity": " 28",
      "ChargVelocity": " 24",
      "ChangeUp": " 1"
    },
    {
      "Name": "Red Pianta",
      "Bat": " 8",
      "Lean": " 0",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.25",
      "ReachOut": " 0.75",
      "ReachIn": " 0.5",
      "Run": " 2",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 7",
      "Pitch": " 4",
      "Stamina": " 7",
      "Curve": " 2.5",
      "Velocity": " 27",
      "ChargVelocity": " 24",
      "ChangeUp": " 1"
    },
    {
      "Name": "Yellow Pianta",
      "Bat": " 8",
      "Lean": " 0",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.25",
      "ReachOut": " 0.75",
      "ReachIn": " 0.5",
      "Run": " 2",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 7",
      "Pitch": " 4",
      "Stamina": " 5",
      "Curve": " 2.5",
      "Velocity": " 27",
      "ChargVelocity": " 23",
      "ChangeUp": " 1"
    },
    {
      "Name": "Blue Noki",
      "Bat": " 4",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 7",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 5",
      "Stamina": " 5",
      "Curve": " 6.5",
      "Velocity": " 34",
      "ChargVelocity": " 23",
      "ChangeUp": " 2"
    },
    {
      "Name": "Red Noki",
      "Bat": " 4",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 7",
      "Field": " 5",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 4",
      "Stamina": " 5",
      "Curve": " 5.5",
      "Velocity": " 34",
      "ChargVelocity": " 23",
      "ChangeUp": " 1"
    },
    {
      "Name": "Green Noki",
      "Bat": " 5",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.75",
      "ReachOut": " 0.75",
      "ReachIn": " 1",
      "Run": " 7",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 1",
      "Arm": " 1",
      "Jump": " 2",
      "Chemistry": " 5",
      "Pitch": " 4",
      "Stamina": " 5",
      "Curve": " 5.5",
      "Velocity": " 34",
      "ChargVelocity": " 23",
      "ChangeUp": " 1"
    },
    {
      "Name": "Green Kritter",
      "Bat": " 7",
      "Lean": " 3",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8",
      "ReachOut": " 1",
      "ReachIn": " 1",
      "Run": " 3",
      "Field": " 7",
      "Dive": " 3",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 2",
      "Pitch": " 4",
      "Stamina": " 7",
      "Curve": " 3",
      "Velocity": " 34",
      "ChargVelocity": " 22",
      "ChangeUp": " 1"
    },
    {
      "Name": "Blue Kritter",
      "Bat": " 6",
      "Lean": " 3",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8",
      "ReachOut": " 1",
      "ReachIn": " 1",
      "Run": " 3",
      "Field": " 7",
      "Dive": " 3",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 2",
      "Pitch": " 5",
      "Stamina": " 7",
      "Curve": " 4",
      "Velocity": " 34",
      "ChargVelocity": " 22",
      "ChangeUp": " 1"
    },
    {
      "Name": "Red Kritter",
      "Bat": " 8",
      "Lean": " 3",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8",
      "ReachOut": " 1",
      "ReachIn": " 1",
      "Run": " 3",
      "Field": " 7",
      "Dive": " 3",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 2",
      "Pitch": " 3",
      "Stamina": " 7",
      "Curve": " 2.5",
      "Velocity": " 32",
      "ChargVelocity": " 24",
      "ChangeUp": " 1"
    },
    {
      "Name": "Brown Kritter",
      "Bat": " 7",
      "Lean": " 3",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8",
      "ReachOut": " 1",
      "ReachIn": " 1",
      "Run": " 4",
      "Field": " 7",
      "Dive": " 3",
      "Size": " 3",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 2",
      "Pitch": " 3",
      "Stamina": " 7",
      "Curve": " 3",
      "Velocity": " 32",
      "ChargVelocity": " 22",
      "ChangeUp": " 1"
    },
    {
      "Name": "Green Koopa Troopa",
      "Bat": " 6",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 6",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 9",
      "Pitch": " 3",
      "Stamina": " 6",
      "Curve": " 5",
      "Velocity": " 31",
      "ChargVelocity": " 23",
      "ChangeUp": " 2"
    },
    {
      "Name": "Red Koopa Paratroopa",
      "Bat": " 4",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 5",
      "Field": " 7",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 3",
      "Chemistry": " 6",
      "Pitch": " 4",
      "Stamina": " 6",
      "Curve": " 5.5",
      "Velocity": " 34",
      "ChargVelocity": " 25",
      "ChangeUp": " 2"
    },
    {
      "Name": "Red Koopa Troopa",
      "Bat": " 6",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 6",
      "Field": " 3",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 9",
      "Pitch": " 4",
      "Stamina": " 6",
      "Curve": " 4.5",
      "Velocity": " 32",
      "ChargVelocity": " 24",
      "ChangeUp": " 2"
    },
    {
      "Name": "Green Koopa Paratroopa",
      "Bat": " 5",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 5",
      "Field": " 7",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 3",
      "Chemistry": " 6",
      "Pitch": " 3",
      "Stamina": " 6",
      "Curve": " 4.5",
      "Velocity": " 34",
      "ChargVelocity": " 25",
      "ChangeUp": " 2"
    },
    {
      "Name": "Blue Magikoopa",
      "Bat": " 2",
      "Lean": " 0.5",
      "Zone": " 1",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 0.75",
      "ReachIn": " 0.75",
      "Run": " 2",
      "Field": " 8",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 6",
      "Pitch": " 8",
      "Stamina": " 4",
      "Curve": " 8",
      "Velocity": " 38",
      "ChargVelocity": " 29",
      "ChangeUp": " 4"
    },
    {
      "Name": "Red Magikoopa",
      "Bat": " 3",
      "Lean": " 0.5",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 0.75",
      "ReachIn": " 0.75",
      "Run": " 1",
      "Field": " 8",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 6",
      "Pitch": " 8",
      "Stamina": " 4",
      "Curve": " 8.5",
      "Velocity": " 38",
      "ChargVelocity": " 31",
      "ChangeUp": " 4"
    },
    {
      "Name": "Green Magikoopa",
      "Bat": " 2",
      "Lean": " 0.5",
      "Zone": " 1",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 0.75",
      "ReachIn": " 0.75",
      "Run": " 2",
      "Field": " 8",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 6",
      "Pitch": " 7",
      "Stamina": " 4",
      "Curve": " 10",
      "Velocity": " 45",
      "ChargVelocity": " 36",
      "ChangeUp": " 4"
    },
    {
      "Name": "Yellow Magikoopa",
      "Bat": " 3",
      "Lean": " 0.5",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 0.75",
      "ReachIn": " 0.75",
      "Run": " 2",
      "Field": " 8",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 6",
      "Pitch": " 7",
      "Stamina": " 4",
      "Curve": " 10",
      "Velocity": " 46",
      "ChargVelocity": " 33",
      "ChangeUp": " 4"
    },
    {
      "Name": "Hammer Bro",
      "Bat": " 7",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8",
      "ReachOut": " 1",
      "ReachIn": " 1",
      "Run": " 3",
      "Field": " 6",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 6",
      "Pitch": " 4",
      "Stamina": " 8",
      "Curve": " 3",
      "Velocity": " 28",
      "ChargVelocity": " 21",
      "ChangeUp": " 1.5"
    },
    {
      "Name": "Fire Bro",
      "Bat": " 8",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8",
      "ReachOut": " 1",
      "ReachIn": " 1",
      "Run": " 3",
      "Field": " 6",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 6",
      "Pitch": " 3",
      "Stamina": " 7",
      "Curve": " 2.5",
      "Velocity": " 28",
      "ChargVelocity": " 24",
      "ChangeUp": " 1.5"
    },
    {
      "Name": "Boomerang Bro",
      "Bat": " 7",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8",
      "ReachOut": " 1",
      "ReachIn": " 1",
      "Run": " 3",
      "Field": " 5",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 3",
      "Jump": " 2",
      "Chemistry": " 6",
      "Pitch": " 5",
      "Stamina": " 6",
      "Curve": " 5.5",
      "Velocity": " 31",
      "ChargVelocity": " 24",
      "ChangeUp": " 1.5"
    },
    {
      "Name": "White Dry Bones",
      "Bat": " 7",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8.25",
      "ReachOut": " 0.5",
      "ReachIn": " 1.75",
      "Run": " 5",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 4",
      "Stamina": " 4",
      "Curve": " 3.5",
      "Velocity": " 30",
      "ChargVelocity": " 21",
      "ChangeUp": " 2"
    },
    {
      "Name": "Green Dry Bones",
      "Bat": " 7",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8.5",
      "ReachOut": " 0.75",
      "ReachIn": " 1.75",
      "Run": " 6",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 3",
      "Stamina": " 5",
      "Curve": " 3",
      "Velocity": " 31",
      "ChargVelocity": " 26",
      "ChangeUp": " 2"
    },
    {
      "Name": "Dark Dry Bones",
      "Bat": " 7",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8.5",
      "ReachOut": " 0.75",
      "ReachIn": " 1.75",
      "Run": " 5",
      "Field": " 4",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 5",
      "Stamina": " 5",
      "Curve": " 4",
      "Velocity": " 32",
      "ChargVelocity": " 24",
      "ChangeUp": " 2"
    },
    {
      "Name": "Blue Dry Bones",
      "Bat": " 7",
      "Lean": " 2",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 8.5",
      "ReachOut": " 0.75",
      "ReachIn": " 1.75",
      "Run": " 5",
      "Field": " 5",
      "Dive": " 2",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 3",
      "Stamina": " 5",
      "Curve": " 3",
      "Velocity": " 31",
      "ChargVelocity": " 26",
      "ChangeUp": " 2"
    },
    {
      "Name": "Red Shy Guy",
      "Bat": " 5",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 4",
      "Field": " 7",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 4",
      "Stamina": " 6",
      "Curve": " 5",
      "Velocity": " 35",
      "ChargVelocity": " 27",
      "ChangeUp": " 1.5"
    },
    {
      "Name": "Blue Shy Guy",
      "Bat": " 4",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 4",
      "Field": " 7",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 5",
      "Stamina": " 6",
      "Curve": " 5.5",
      "Velocity": " 35",
      "ChargVelocity": " 25",
      "ChangeUp": " 2"
    },
    {
      "Name": "Yellow Shy Guy",
      "Bat": " 4",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 5",
      "Field": " 7",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 4",
      "Stamina": " 6",
      "Curve": " 5",
      "Velocity": " 35",
      "ChargVelocity": " 27",
      "ChangeUp": " 1.5"
    },
    {
      "Name": "Green Shy Guy",
      "Bat": " 5",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 5",
      "Field": " 7",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 3",
      "Stamina": " 6",
      "Curve": " 5",
      "Velocity": " 37",
      "ChargVelocity": " 27",
      "ChangeUp": " 1.5"
    },
    {
      "Name": "Gray Shy Guy",
      "Bat": " 4",
      "Lean": " 1",
      "Zone": " 2",
      "Agility": " 2",
      "Coverage": " 7.5",
      "ReachOut": " 1",
      "ReachIn": " 0.5",
      "Run": " 4",
      "Field": " 8",
      "Dive": " 3",
      "Size": " 2",
      "Arm": " 2",
      "Jump": " 2",
      "Chemistry": " 4",
      "Pitch": " 4",
      "Stamina": " 7",
      "Curve": " 5",
      "Velocity": " 37",
      "ChargVelocity": " 26",
      "ChangeUp": " 1.5"
    },
  {
    "Name": "Mii",
    "Bat": " 6",
    "Lean": " 2",
    "Zone": " 2",
    "Agility": " 2",
    "Coverage": " 7.75",
    "ReachOut": " 0.75",
    "ReachIn": " 1",
    "Run": " 6",
    "Field": " 6",
    "Dive": " 2",
    "Size": " 2",
    "Arm": " 3",
    "Jump": " 2",
    "Chemistry": " 10",
    "Pitch": " 6",
    "Stamina": " 7",
    "Curve": " 4",
    "Velocity": " 34",
    "ChargVelocity": " 23",
    "ChangeUp": " 1.5"
  }

]